name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Get tag
        id: get_tag
        run: |
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=tag::${GITHUB_REPOSITORY,,}:zammad-legacy-ssl-${GITHUB_REF/refs\/tags\//}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          build-args: VERSION=${{ steps.get_tag.outputs.version }}
          push: true
          tags: ${{ steps.get_tag.outputs.tag }}
